config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/organizations', to: 'organizations#index'

  get '/organizations/:id/pull_requests', to: 'organizations#pull_requests', as: :pull_requests_for_org
end

app/models/user.rb
class User

  attr_reader :provider, :uid, :name

  def initialize(auth_hash)
    @provider= auth_hash[:provider]
    @uid= auth_hash[:uid]
    @name= auth_hash[:info][:name]
    @email= auth_hash[:info][:email]
    @avatar= auth_hash[:info][:image]
    @token= auth_hash[:credentials][:token]
    @nickname= auth_hash[:info][:nickname]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  before_action :set_client

  def logged_in?
    !!session[:token] #double negation to convert to boolean
  end

  def current_user
    @current_user ||=  session[:user]#memoized
  end

  def set_client
    Octokit.auto_paginate = true
    @client = Octokit::Client.new(access_token: session[:token])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @orgs = @client.organizations
  end

  def pull_requests
    @org = params[:id]

    @repos = @client.org_repos(@org).map do |repo|
      {
        name: repo[:name],
        pull_requests: get_pull_requests(repo[:name]),
        pull_requests_url: get_pull_requests_url(repo[:name])
      }
    end
  end

  private

  def get_pull_requests(repo)
    @client.pull_requests("#{@org}/#{repo}")
    .map do |pr|
      build_pr(pr)
    end
  end

  def build_pr(pull_request)
    pull_request = pull_request.to_hash.slice(:number, :html_url, :title, :user)
    pull_request[:user] = pull_request[:user].to_hash
    pull_request
  end

  def get_pull_requests_url(repo)
    "https://github.com/#{@org}/#{repo}/pulls"
  end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController

  def index
    @orgs = client.organizations
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end

  def create
    session[:token] = auth_hash["credentials"]["token"]
    redirect_to organizations_path
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/views/home/index.html.erb
<div class="text-center">
  <h1>Welcome to Big Brother</h1>

  <br>

  This app allows you to check all Pull Requests from all your organizations or repositories at just one place.

  <br>
  <br>

  <%= link_to icon('github fa-fw') + 'Log In with Github', login_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BigBrother</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/organizations/_pull_request.html.erb
<%= link_to pr[:html_url], class: "list-group-item", target: '_blank'  do %>
  <div class="row">
    <div class="col-xs-10">
      <%= "##{pr[:number]} - #{pr[:title]}" %>
    </div>
    <div class="col-xs-2">
      <%= image_tag pr[:user][:avatar_url], class: "pr-avatar pull-right" %>
    </div>
  </div>
<% end %>

app/views/organizations/_repo.html.erb
<% if repo[:pull_requests].present? || params[:all] == "true" %>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
      <%= link_to repo[:pull_requests_url], target: '_blank' do %>
          <strong>
            <%= repo[:name] %> <%= icon('external-link') %>
          </strong>
      <% end %>
    </div>

      <div class="list-group">
        <% repo[:pull_requests].each do |pr| %>
          <%= render 'pull_request', pr: pr %>
        <% end %>
      </div>

      <% if repo[:pull_requests].blank? %>
        <p>
          No PRs here!
        </p>
      <% end %>

      <div class="panel-footer">
        Total: <%= repo[:pull_requests].length %>
      </div>
    </div>
  </div>
<% end %>

app/views/organizations/index.html.erb
<%= render 'shared/logout' %>

<br>

<h1>Your Organizations</h1>

<p>
  Choose the org you want to check all Pull Requests
</p>

<div class="row">
  <% @orgs.each do |org| %>
    <%= link_to pull_requests_for_org_path(org.login)  do %>
      <div class="col-md-2">
        <div class="panel panel-default text-center">
          <div class="panel-body">
            <div class="text-muted">
              <%= icon('github-alt fa-5x') %> <br>
            </div>
            <%= org.login  %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/organizations/pull_requests.html.erb
<h1>
  <%= @org %> - Pull Requests
</h1>

<div class="pull-right">
  <% if params[:all] == "true" %>
    <%= link_to 'see only projects with PRs opened', pull_requests_for_org_path(@org)  %>
  <% else %>
    <%= link_to 'see all projects', pull_requests_for_org_path(@org, all: true) %>
  <% end %>
</div>

<br>

<%= link_to organizations_path do %>
  <div class="btn btn-default">
    <%= icon('arrow-left fa-fw') %> Back to orgs
  </div>
<% end %>

<hr>

<div class="row">
  <% @repos.each do |repository| %>
    <%= render 'repo', repo: repository %>
  <% end %>
</div>

app/views/pull_requests/index.html.erb
<div class="btn btn-default">

</div>

<%= render 'shared/logout' %>

<br>

<% @orgs.each do |org| %>
  <br>
  <%= org.login %>
<% end %>

app/views/shared/_logout.html.erb
<%= link_to icon('sign-out fa fw') + 'Log Out', logout_path, class: "btn btn-default" %>